project:
  type: book

book:
  title: "Advanced Data Analytics Course"
  author: "Andrés Pérez-Coronado"
  date: "02/08/2025"
  chapters:
    - index.qmd
    - 1-Issue-for-Decision-Making.qmd
    - 2-Key-Players-and-Topics.qmd
    - 3-Imputing-and-Linking-Data.qmd
    - 4-Spotting-Weak-Predictive-Signals.qmd
    - 5-Data-Storage-and-Traceability.qmd
    - 6-Interpreting-Weak-Predictive-Signals.qmd    
    - 7-Planning-and-Taking-Action.qmd
    - 8-Monitoring-and-Assessing-Progress.qmd
    - references.qmd
    - Appendix-1.qmd

bibliography: references.bib

format:
  html:
    number-sections: true
    toc: true
    toc-depth: 2
  pdf:
    number-sections: true
    toc: true
    toc-depth: 2

editor: visual

resources:
    - Andres_Perez_resume_EN-4.pdf
